
spring:
   mvc:
      favicon:
         enabled: false

logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO

esign:
   maintenance:
        log:
             filename: /logs/maintenance/esignmaintenance 
server:
  port: 8081
  contextPath: /maintenance
